---
- name: Uninstall ufw
  become: yes
  apt:
    name: firewalld
    state: absent
    purge: yes

- name: Install firewalld
  become: yes
  apt:
    name: firewalld
    state: latest

- name: Enable firewalld service
  become: yes
  service:
    state: started
    enabled: yes
    name: firewalld

- name: Allow SSH connections
  become: yes
  shell: firewall-cmd --permanent --zone=public --add-port={{ ssh_port }}/tcp

- name: Allow HTTPS
  become: yes
  shell: firewall-cmd --permanent --zone=public --add-service="https"

- name: Allow HTTP
  become: yes
  shell: firewall-cmd --permanent --zone=public --add-service="http"

- name: Enable firewall
  become: yes
  shell: firewall-cmd --reload

- name: Copy sshd_config to host
  become: yes
  template:
    owner: root
    group: root
    mode: 0644
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config

- name: Restart sshd
  become: yes
  service:
    name: sshd
    state: restarted
