# vim:ft=yaml.ansible
- name: Create `www` group
  tags: web,base
  become: yes
  group:
    name: www

- name: Create `www` user
  tags: web,base
  become: yes
  user:
    home: /var/www
    create_home: yes
    group: www
    name: www

- name: Install nginx
  tags: web
  become: yes
  apt:
    name: nginx
    state: latest

- name: Disable default nginx site
  tags: web
  become: true
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Enable nginx service
  tags: web
  become: yes
  service:
    name: nginx
    enabled: yes
    state:  started

- name: Install postgresql
  tags: web,database
  become: yes
  apt:
    name: postgresql
    state: latest

- name: Enable postgresql
  tags: web,database
  become: yes
  service:
    name: postgresql
    state: started
    enabled: yes
