- name: Install docker and docker-compose dependencies
  tags: containers,debian
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  become: true
  apt:
    name: ca-certificates,curl,gnupg,lsb-release
    state: latest

- name: Add docker repo
  tags: containers,centos
  when: ansible_distribution == "AlmaLinux" or ansible_distribution == "CentOS"
  become: true
  yum_repository:
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Remove podman and buildah packages
  tags: containers,centos
  when: ansible_distribution == "AlmaLinux" or ansible_distribution == "CentOS"
  become: true
  dnf:
    name: podman,buildah
    state: absent

- name: Adding Docker's GPG key
  tags: containers,debian
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  become: true
  shell:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
    cmd:  curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Find out server's architecture
  tags: containers
  become: true
  changed_when: false
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Adding Docker's repo
  tags: containers
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  become: true
  template:
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: 0644
    src: docker.list.j2

- name: Install docker
  tags: containers
  become: true
  package:
    state: latest
    name: docker-ce,docker-ce-cli,containerd.io
    update_cache: true

- name: Install docker-compose
  tags: containers
  become: true
  uri:
    creates: /usr/local/bin/docker-compose
    url: https://github.com/docker/compose/releases/download/v2.3.2/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
    owner: root
    group: root

- name: Add docker service to autostart and start it
  tags: containers
  become: true
  service:
    name: docker
    enabled: yes
    state: started

- name: Add containerd service to autostart and start it
  tags: containers
  become: true
  service:
    name: containerd
    enabled: yes
    state: started

- name: Create docker group
  tags: containers
  become: true
  group:
    name: docker

- name: Add user to docker group
  tags: containers
  become: true
  user:
    append: yes
    name: "{{ user_name }}"
    groups:
      - docker
