- name: Create `sudo` group
  become: yes
  group:
    name: sudo

- name: Copy `99-sudo` file to `/etc/sudoers.d/`
  become: yes
  copy:
    owner: root
    group: root
    mode: 0640
    src: 99-sudo
    dest: /etc/sudoers.d/99-sudo

- name: Create user
  become: yes
  user:
    password: "{{ user_password | password_hash('sha512') }}"
    name: "{{ user_name }}"
    shell: /usr/bin/zsh
    group: users
    groups:
      - sudo
